__author__ = 'Faris Chugthai'
__copyright__ = 'Copyright (C) 2018 Faris Chugthai'
__description__ = 'Functional scripts for regular use at any workstation.'
__docformat__ = 'reStructuredText'
__email__ = 'farischugthai@gmail.com'
__license__ = 'MIT'
__title__ = 'utilities'
__package_name__ = 'utilities'
