__author__ = 'Faris Chugthai'
__copyright__ = 'Copyright (C) 2018 Faris Chugthai'
__description__ = 'Functional scripts for regular use at any workstation.'
__docformat__ = 'reStructuredText'
__license__ = 'MIT'
__title__ = 'utilities'
__package_name__ = 'utilities'
__version_info__ = (0, 0, 1)
__version__ = ".".join(map(str, __version_info__))
